### ISSUE TITLE
Can't run demo code

### ISSUE THREAD

**Issue by yestaehyung** [xushilin1/FashionFormer#3]
hello when i run demo code there was some error

python demo/image_demo.py ../dataset/test/03fc99c4deaf14724ef6277dec16b8e8.jpg work_dirs/attribute_mask_rcnn_swin_b_3x/attribute_mask_rcnn_swin_b_3x.py work_dirs/attribute_mask_rcnn_swin_b_3x/latest.pth

how can i solve this error?

Traceback (most recent call last):
  File "/home/kshan/anaconda3/envs/fashionformer/lib/python3.8/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/kshan/anaconda3/envs/fashionformer/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'datasets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/image_demo.py", line 69, in <module>
    main(args)
  File "demo/image_demo.py", line 35, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home/kshan/taehyung/mmdetection/mmdet/apis/inference.py", line 33, in init_detector
    config = mmcv.Config.fromfile(config)
  File "/home/kshan/anaconda3/envs/fashionformer/lib/python3.8/site-packages/mmcv/utils/config.py", line 343, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/kshan/anaconda3/envs/fashionformer/lib/python3.8/site-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError

**Comment by xushilin1** [comment]
Thanks for your interest in our work.  
I think you can try the command like this.
 `PYTHONPATH='.' python demo/image_demo.py ...`

**Comment by abaybektursun** [comment]
Same issue here. I tried 
```bash
PYTHONPATH='.' python demo/image_demo.py demo.jpg configs/fashionformer/fashionpedia/fashionformer_r50_mlvl_feat_3x.py fashionformer_r50_3x.pth
```
Same error.

**Comment by abaybektursun** [comment]
I was able to solve this error by installing depedencies that are missing in the readme.
```bash
pip install git+https://github.com/cocodataset/panopticapi.git
pip install sklearn
pip install scikit-image
```
However, another issue came to its place:
```
Traceback (most recent call last):
  File "demo/image_demo.py", line 68, in <module>
    main(args)
  File "demo/image_demo.py", line 34, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home/abaybektursun/projects/Product_Labels_Ejike_Uzoigwe/FashionFormer/venv/lib/python3.8/site-packages/mmdet/apis/inference.py", line 33, in init_detector
    config = mmcv.Config.fromfile(config)
  File "/home/abaybektursun/projects/Product_Labels_Ejike_Uzoigwe/FashionFormer/venv/lib/python3.8/site-packages/mmcv/utils/config.py", line 335, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/abaybektursun/projects/Product_Labels_Ejike_Uzoigwe/FashionFormer/venv/lib/python3.8/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/abaybektursun/projects/Product_Labels_Ejike_Uzoigwe/FashionFormer/projects/FashionFormer/__init__.py", line 2, in <module>
    from .kernel_roi_head import KernelIterHead
  File "/home/abaybektursun/projects/Product_Labels_Ejike_Uzoigwe/FashionFormer/projects/FashionFormer/kernel_roi_head.py", line 8, in <module>
    from models.assigner.mask_pseudo_sampler import MaskPseudoSampler
  File "/home/abaybektursun/projects/Product_Labels_Ejike_Uzoigwe/FashionFormer/models/assigner/__init__.py", line 1, in <module>
    from .mask_hungarian_assigner import DiceCost, MaskCost, MaskHungarianAssigner
  File "/home/abaybektursun/projects/Product_Labels_Ejike_Uzoigwe/FashionFormer/models/assigner/mask_hungarian_assigner.py", line 15, in <module>
    class DiceCost(object):
  File "/home/abaybektursun/projects/Product_Labels_Ejike_Uzoigwe/FashionFormer/venv/lib/python3.8/site-packages/mmcv/utils/registry.py", line 311, in _register
    self._register_module(
  File "/home/abaybektursun/projects/Product_Labels_Ejike_Uzoigwe/FashionFormer/venv/lib/python3.8/site-packages/mmcv/utils/registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'DiceCost is already registered in Match Cost'
```

**Comment by xushilin1** [comment]
Thanks for your interest and sorry for the late reply.
I have reproduced this issue and fixed this bug in mmdet==2.18.0;

**Comment by danailliu** [comment]
hello，when I run the demo. ALL the coordinate of BBOX is zero.like this:

[array([[0.        , 0.        , 0.        , 0.        , 0.79686284]],
       dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.05989303]],
       dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([[0.       , 0.       , 0.       , 0.       , 0.0524485]],
       dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.02910043],
        [0.        , 0.        , 0.        , 0.        , 0.02114534],
        [0.        , 0.        , 0.        , 0.        , 0.01676908],
        [0.        , 0.        , 0.        , 0.        , 0.01669254]],
       dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.02301841],
        [0.        , 0.        , 0.        , 0.        , 0.01924651]],
       dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.03298811]],
       dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.01731287]],
       dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.89752316]],
       dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.06933805],
        [0.        , 0.        , 0.        , 0.        , 0.05986979],
        [0.        , 0.        , 0.        , 0.        , 0.02281323],
        [0.        , 0.        , 0.        , 0.        , 0.01794562]],
       dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.90336406],
        [0.        , 0.        , 0.        , 0.        , 0.5355902 ],
        [0.        , 0.        , 0.        , 0.        , 0.33188647],
        [0.        , 0.        , 0.        , 0.        , 0.03402795],
        [0.        , 0.        , 0.        , 0.        , 0.02057427],
        [0.        , 0.        , 0.        , 0.        , 0.01929876]],
       dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.77538824],
        [0.        , 0.        , 0.        , 0.        , 0.7699898 ],
        [0.        , 0.        , 0.        , 0.        , 0.04109826],
        [0.        , 0.        , 0.        , 0.        , 0.03557413],
        [0.        , 0.        , 0.        , 0.        , 0.03185431],
        [0.        , 0.        , 0.        , 0.        , 0.03024532],
        [0.        , 0.        , 0.        , 0.        , 0.02898962],
        [0.        , 0.        , 0.        , 0.        , 0.02549006],
        [0.        , 0.        , 0.        , 0.        , 0.02261182],
        [0.        , 0.        , 0.        , 0.        , 0.02258267],
        [0.        , 0.        , 0.        , 0.        , 0.02063485],
        [0.        , 0.        , 0.        , 0.        , 0.02014134],
        [0.        , 0.        , 0.        , 0.        , 0.01998736],
        [0.        , 0.        , 0.        , 0.        , 0.01909333],
        [0.        , 0.        , 0.        , 0.        , 0.01787589],
        [0.        , 0.        , 0.        , 0.        , 0.01767974],
        [0.        , 0.        , 0.        , 0.        , 0.01759748],
        [0.        , 0.        , 0.        , 0.        , 0.01683186]],
       dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.02470406],
        [0.        , 0.        , 0.        , 0.        , 0.0189336 ],
        [0.        , 0.        , 0.        , 0.        , 0.01676438]],
       dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([[0.        , 0.        , 0.        , 0.        , 0.03116137]],
       dtype=float32),

**Comment by ranjeetthakur193** [comment]
Spent whole day can't setup the environment, Better to add a colab notebook or a docker image

**Comment by AndyMcPython** [comment]
> Spent whole day can't setup the environment, Better to add a colab notebook or a docker image

The following setup worked for me on colab: 
absl-py==1.4.0
alabaster==0.7.13
albumentations==1.2.1
altair==4.2.2
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arviz==0.15.1
astropy==5.2.2
astunparse==1.6.3
attrs==22.2.0
audioread==3.0.0
autograd==1.5
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.11.2
bleach==6.0.0
blis==0.7.9
blosc2==2.0.0
bokeh==2.4.3
branca==0.6.0
CacheControl==0.12.11
cached-property==1.5.2
cachetools==5.3.0
catalogue==2.0.8
certifi==2022.12.7
cffi==1.15.1
chardet==4.0.0
charset-normalizer==2.0.12
chex==0.1.7
click==8.1.3
cloudpickle==2.2.1
cmake==3.25.2
cmdstanpy==1.1.0
colorcet==3.0.1
colorlover==0.3.0
community==1.0.0b1
confection==0.0.4
cons==0.4.5
contextlib2==0.6.0.post1
contourpy==1.0.7
convertdate==2.4.0
cryptography==40.0.1
cufflinks==0.17.3
cupy-cuda11x==11.0.0
cvxopt==1.3.0
cvxpy==1.3.1
cycler==0.11.0
cymem==2.0.7
Cython==0.29.34
dask==2022.12.1
datascience==0.17.6
db-dtypes==1.1.1
dbus-python==1.2.16
debugpy==1.6.6
decorator==4.4.2
defusedxml==0.7.1
distributed==2022.12.1
dlib==19.24.1
dm-tree==0.1.8
docutils==0.16
dopamine-rl==4.0.6
earthengine-api==0.1.348
easydict==1.10
ecos==2.0.12
editdistance==0.6.2
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl
entrypoints==0.4
ephem==4.1.4
et-xmlfile==1.1.0
etils==1.2.0
etuples==0.3.8
exceptiongroup==1.1.1
fastai==2.7.12
fastcore==1.5.29
fastdownload==0.0.7
fastjsonschema==2.16.3
fastprogress==1.0.3
fastrlock==0.8.1
filelock==3.11.0
firebase-admin==5.3.0
Flask==2.2.3
flatbuffers==23.3.3
flax==0.6.8
folium==0.14.0
fonttools==4.39.3
frozendict==2.3.6
fsspec==2023.3.0
future==0.18.3
gast==0.4.0
GDAL==3.3.2
gdown==4.6.6
gensim==4.3.1
geographiclib==2.0
geopy==2.3.0
gin-config==0.5.0
glob2==0.7
google==2.0.3
google-api-core==2.11.0
google-api-python-client==2.84.0
google-auth==2.17.2
google-auth-httplib2==0.1.0
google-auth-oauthlib==1.0.0
google-cloud-bigquery==3.9.0
google-cloud-bigquery-storage==2.19.1
google-cloud-core==2.3.2
google-cloud-datastore==2.15.1
google-cloud-firestore==2.11.0
google-cloud-language==2.9.1
google-cloud-storage==2.8.0
google-cloud-translate==3.11.1
google-colab @ file:///colabtools/dist/google-colab-1.0.0.tar.gz
google-crc32c==1.5.0
google-pasta==0.2.0
google-resumable-media==2.4.1
googleapis-common-protos==1.59.0
googledrivedownloader==0.4
graphviz==0.20.1
greenlet==2.0.2
grpcio==1.53.0
grpcio-status==1.48.2
gspread==3.4.2
gspread-dataframe==3.0.8
gym==0.25.2
gym-notices==0.0.8
h5netcdf==1.1.0
h5py==3.8.0
HeapDict==1.0.1
hijri-converter==2.2.4
holidays==0.22
holoviews==1.15.4
html5lib==1.1
httpimport==1.3.0
httplib2==0.21.0
humanize==4.6.0
hyperopt==0.2.7
idna==3.4
imageio==2.25.1
imageio-ffmpeg==0.4.8
imagesize==1.4.1
imbalanced-learn==0.10.1
imgaug==0.4.0
importlib-metadata==6.2.0
importlib-resources==5.12.0
imutils==0.5.4
inflect==6.0.4
iniconfig==2.0.0
intel-openmp==2023.1.0
ipykernel==5.5.6
ipython==7.34.0
ipython-genutils==0.2.0
ipython-sql==0.4.1
ipywidgets==7.7.1
itsdangerous==2.1.2
jax==0.4.7
jaxlib @ https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.4.7+cuda11.cudnn86-cp39-cp39-manylinux2014_x86_64.whl
jieba==0.42.1
Jinja2==3.1.2
joblib==1.2.0
jsonpickle==3.0.1
jsonschema==4.3.3
jupyter-client==6.1.12
jupyter-console==6.1.0
jupyter-server==1.23.6
jupyter_core==5.3.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
kaggle==1.5.13
keras==2.12.0
keras-vis==0.4.1
kiwisolver==1.4.4
korean-lunar-calendar==0.3.1
langcodes==3.3.0
lazy_loader==0.2
libclang==16.0.0
librosa==0.10.0.post2
lightgbm==3.3.5
lit==16.0.0
llvmlite==0.39.1
locket==1.0.0
logical-unification==0.4.5
LunarCalendar==0.0.9
lxml==4.9.2
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.7.1
matplotlib-inline==0.1.6
matplotlib-venn==0.11.9
mdurl==0.1.2
miniKanren==1.0.3
missingno==0.5.2
mistune==0.8.4
mizani==0.8.1
mkl==2019.0
ml-dtypes==0.0.4
mlxtend==0.14.0
more-itertools==9.1.0
moviepy==1.0.3
mpmath==1.3.0
msgpack==1.0.5
multipledispatch==0.6.0
multitasking==0.0.11
murmurhash==1.0.9
music21==8.1.0
natsort==8.3.1
nbclient==0.7.3
nbconvert==6.5.4
nbformat==5.8.0
nest-asyncio==1.5.6
networkx==3.1
nibabel==3.0.2
nltk==3.8.1
notebook==6.4.8
numba==0.56.4
numexpr==2.8.4
numpy==1.22.4
oauth2client==4.1.3
oauthlib==3.2.2
opencv-contrib-python==4.7.0.72
opencv-python==4.7.0.72
opencv-python-headless==4.7.0.72
openpyxl==3.0.10
opt-einsum==3.3.0
optax==0.1.4
orbax==0.1.7
osqp==0.6.2.post0
packaging==23.0
palettable==3.3.1
pandas==1.5.3
pandas-datareader==0.10.0
pandas-gbq==0.17.9
pandocfilters==1.5.0
panel==0.14.4
param==1.13.0
parso==0.8.3
partd==1.3.0
pathlib==1.0.1
pathy==0.10.1
patsy==0.5.3
pep517==0.13.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.4.0
pip-tools==6.6.2
platformdirs==3.2.0
plotly==5.13.1
plotnine==0.10.1
pluggy==1.0.0
pooch==1.6.0
portpicker==1.3.9
prefetch-generator==1.0.3
preshed==3.0.8
prettytable==0.7.2
proglog==0.1.10
progressbar2==4.2.0
prometheus-client==0.16.0
promise==2.3
prompt-toolkit==3.0.38
prophet==1.1.2
proto-plus==1.22.2
protobuf==3.20.3
psutil==5.9.4
psycopg2==2.9.6
ptyprocess==0.7.0
py-cpuinfo==9.0.0
py4j==0.10.9.7
pyarrow==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocotools==2.0.6
pycparser==2.21
pyct==0.5.0
pydantic==1.10.7
pydata-google-auth==1.7.0
pydot==1.4.2
pydot-ng==2.0.0
pydotplus==2.0.2
PyDrive==1.3.1
pyerfa==2.0.0.3
pygame==2.3.0
Pygments==2.14.0
PyGObject==3.36.0
pymc==5.1.2
PyMeeus==0.5.12
pymystem3==0.2.0
PyOpenGL==3.1.6
pyparsing==3.0.9
pyrsistent==0.19.3
PySocks==1.7.1
pytensor==2.10.1
pytest==7.2.2
python-apt==0.0.0
python-dateutil==2.8.2
python-louvain==0.16
python-slugify==8.0.1
python-utils==3.5.2
pytz==2022.7.1
pytz-deprecation-shim==0.1.0.post0
pyviz-comms==2.2.1
PyWavelets==1.4.1
PyYAML==6.0
pyzmq==23.2.1
qdldl==0.1.7
qudida==0.0.4
regex==2022.10.31
requests==2.27.1
requests-oauthlib==1.3.1
requests-unixsocket==0.2.0
rich==13.3.3
rpy2==3.5.5
rsa==4.9
scikit-image==0.19.3
scikit-learn==1.2.2
scipy==1.10.1
scs==3.2.3
seaborn==0.12.2
Send2Trash==1.8.0
shapely==2.0.1
six==1.16.0
sklearn-pandas==2.2.0
smart-open==6.3.0
sniffio==1.3.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soundfile==0.12.1
soupsieve==2.4
soxr==0.3.4
spacy==3.5.1
spacy-legacy==3.0.12
spacy-loggers==1.0.4
Sphinx==3.5.4
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
SQLAlchemy==2.0.9
sqlparse==0.4.3
srsly==2.4.6
statsmodels==0.13.5
sympy==1.11.1
tables==3.8.0
tabulate==0.8.10
tblib==1.7.0
tenacity==8.2.2
tensorboard==2.12.1
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
tensorflow==2.12.0
tensorflow-datasets==4.8.3
tensorflow-estimator==2.12.0
tensorflow-gcs-config==2.12.0
tensorflow-hub==0.13.0
tensorflow-io-gcs-filesystem==0.32.0
tensorflow-metadata==1.13.0
tensorflow-probability==0.19.0
tensorstore==0.1.35
termcolor==2.2.0
terminado==0.17.1
text-unidecode==1.3
textblob==0.17.1
tf-slim==1.1.0
thinc==8.1.9
threadpoolctl==3.1.0
tifffile==2023.3.21
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
torch @ https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp39-cp39-linux_x86_64.whl
torchaudio @ https://download.pytorch.org/whl/cu118/torchaudio-2.0.1%2Bcu118-cp39-cp39-linux_x86_64.whl
torchdata==0.6.0
torchsummary==1.5.1
torchtext==0.15.1
torchvision @ https://download.pytorch.org/whl/cu118/torchvision-0.15.1%2Bcu118-cp39-cp39-linux_x86_64.whl
tornado==6.2
tqdm==4.65.0
traitlets==5.7.1
triton==2.0.0
tweepy==4.13.0
typer==0.7.0
typing_extensions==4.5.0
tzdata==2023.3
tzlocal==4.3
uritemplate==4.1.1
urllib3==1.26.15
vega-datasets==0.9.0
wasabi==1.1.1
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.1
Werkzeug==2.2.3
widgetsnbextension==3.6.4
wordcloud==1.8.2.2
wrapt==1.14.1
xarray==2022.12.0
xarray-einstats==0.5.1
xgboost==1.7.5
xlrd==2.0.1
yellowbrick==1.5
yfinance==0.2.14
zict==2.2.0
zipp==3.15.0

**Comment by MroutsideturnAF** [comment]
> Spent whole day can't setup the environment, Better to add a colab notebook or a docker image

The following setup worked for me on colab. 
[pip_freeze.txt](https://github.com/xushilin1/FashionFormer/files/11211840/pip_freeze.txt)

**Comment by anilsathyan7** [comment]
This seems to work, atleast with cpu mode:
```
conda create --name fashionformer python=3.8.13
conda activate fashionformer
conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=11.3 -c pytorch -c conda-forge
pip install -U openmim
mim install mmcv-full==1.4.0
pip install mmdet==2.18.0
pip install git+https://github.com/cocodataset/panopticapi.git
pip3 install -U scikit-learn scipy matplotlib scikit-image chainercv
```
