### ISSUE TITLE
KeyError: 'FashionFormer is not in the models registry'

### ISSUE THREAD

**Issue by Youcunl** [xushilin1/FashionFormer#8]
I used your trained model with config file ‘fashionformer_r50_modanet.py’ to demo my own img, but face the error below. How could I fix the issus?

`(open-mmlab) /mnt/workspace/lyc/FashionFormer-main> PYTHONPATH='.' python demo/image_demo.py /mnt/workspace/lyc/mmdet/demo/demo1.jpg /mnt/workspace/lyc/FashionFormer-main/configs/fashionformer/modanet/fashionformer_r50_modanet.py /mnt/workspace/lyc/FashionFormer-main/fashionformer_r50_3x.pth
/home/pai/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/misc.py:77: UserWarning: projects.KFashion failed to import and is ignored.
  UserWarning)
/home/pai/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/misc.py:77: UserWarning: datasets failed to import and is ignored.
  UserWarning)
Traceback (most recent call last):
  File "demo/image_demo.py", line 68, in <module>
    main(args)
  File "demo/image_demo.py", line 34, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home/pai/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 44, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "/home/pai/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/pai/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/pai/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/pai/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 62, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'FashionFormer is not in the models registry'`

**Comment by xushilin1** [comment]
Thanks for your interest in our project. I have solved this bug already. Please pull the repo for the latest code.
